[config]
default_separator = "line"
seperator_length = 27
enable_emojis = true
time_format = 12
sections = [ "separator", "date", "separator", "important", "todos", "separator", "events", "separator", "schedule" ]