[config]
default_separator = "line"
seperator_length = 27
enable_emojis = true
time_format = 12
data_tree_path = "$HOME/.local/whow/"
config_tree_path = "$HOME/.config/whow"
sections = [ "separator", "datetime", "separator", "important", "todos", "separator", "events", "separator", "schedule" ]