[config]
default_separator = "line"
seperator_length = 27
enable_emojis = true
time_format = 12
cachepath = "{HOME}/.local/whow/"
sections = [ "separator", "datetime", "separator", "important", "todos", "separator", "events", "separator", "schedule" ]