[todos]
    [todos.foo]
        name = "foo"
        due = 2001-09-11 # rip
        categories = [
            "categoryName1",
            "categoryName2"
        ]
        overdue = false
    [todos.bar]
        name = "bar"
        due = 2002-09-11 # 1 year after rip
        categories = [
            "categoryName2",
            "categoryName3"
        ]
    [todos.baz]
        name = "baz"
        due = 2003-09-11 # 2 years after rip
        categories = [
            "categoryName1",
            "categoryName3"
        ]